### PR TITLE
fix: Update @types/node to 16.7.9

### PR DESCRIPTION
**Pull request by cernytomas**
Issue #722 

*Description of changes:*

Updated @types/node to 16.7.8
Renamed `Signer` to `Sign`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

# Check any applicable:
- [ ] Were any files moved? Moving files changes their URL, which breaks all hyperlinks to the files.

### CODE REVIEW

**Review by josecorella — APPROVED** [review]
Hello 👋!

Thank you for contributing to the AWS Encryption SDK JavaScript.
Your changes have been approved!

**Comment by corrjo** [comment]
After this update I'm getting 

```
node_modules/@aws-crypto/material-management-node/build/main/src/material_helpers.d.ts:3:10 - error TS2724: '"crypto"' has no exported member named 'Sign'. Did you mean 'sign'?

3 import { Sign, Verify, createCipheriv, createDecipheriv } from 'crypto';
           ~~~~

  node_modules/@types/node/crypto.d.ts:1159:14
    1159     function sign(
                      ~~~~
    'sign' is declared here.
```

**Comment by corrjo** [comment]
I see, @types/node 14 vs 16 issue. 

I know node 16 is becoming lts in a few weeks, but pushing out a breaking change while the active LTS is 14, and then releasing it as a patch kind of sucks.

**Comment by texastony** [comment]
Howdy @corrjo,

Thank you for bringing this to our attention.
We will issue a rollback.

Our goal is to ensure that our dependencies
are not public in ways that break our customer's code.

Much Obliged,
AWS Crypto Tools

**Comment by tomasstrejcek** [comment]
what a pain :) maybe you could have directly release new minor version supporting new version because both of those are breaking changes, which have no place in a crucial modules like these? :(

**Pull request merged**
