### PR TITLE
chore: upgrade dev dependencies for karma credential management

### PR DESCRIPTION
**Pull request by texastony**
*Issue #, if available:* None

*Description of changes:* Chore: Upgrade aws-sdk provided karma credentials.

The specific commands:
```
npm install @aws-sdk/credential-provider-node@latest --save-dev
npm install @aws-sdk/karma-credential-loader@latest --save-dev
npm install @aws-sdk/util-base64-browser@latest --save-dev
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

# Check any applicable:
- [ ] Were any files moved? Moving files changes their URL, which breaks all hyperlinks to the files.

### CODE REVIEW

**Review by seebees — APPROVED** [review]
LGTM

**Comment by seebees** [comment]
We can do it when we squash the commits, but can you include the specific commands you ran please :)

**Comment by texastony** [comment]
Looking into why the Code Build failed... I see one Test failed during the browser/integration tests... so hopefully a time out.

**Comment by texastony** [comment]
Updated the PR Request with commands ran.

**Pull request merged**
